name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.156.110.29 >> ~/.ssh/known_hosts
      shell: bash

    - name: Sync files to VPS
      run: |
        rsync -avz --exclude '.env' --exclude 'venv' -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ root@185.156.110.29:/root/SH_assist_bot/

    - name: Restart bot service
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@185.156.110.29 "sudo systemctl restart sh_tg_bot"
