name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync files to VPS
      run: |
        rsync -avz --exclude '.env' --exclude 'venv' -e "ssh -o StrictHostKeyChecking=no" ./ root@185.156.110.29:/root/SH_assist_bot/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Restart bot service
      run: |
        ssh -o StrictHostKeyChecking=no root@185.156.110.29 "sudo systemctl restart sh_tg_bot"
